language: php
php:
  - 7.0
  - 7.1
sudo: false
before_install:
  - phpenv config-rm xdebug.ini
install:
  - composer install
before_script:
  - pushd tests
  - php-cgi -b 127.0.0.1:9090 &
  - popd
script:
  - vendor/bin/phpunit
